#!/bin/bash

if [ $# -lt 2 ]
then
 echo "Usage: combine outputfilename [inputfilename ...]" >&2
 exit 1
fi



if [ -e "$1" ]
then
 echo "Error: Output file should not exist" >&2
 exit 1
else
 error="$1"
 shift
 cat "$@" &> "$error"
fi



exit 0

