#!/bin/bash

if [ $# -lt 2 ]
then
   echo "Error: arguments given is less than 2" 1>&2
   exit 1
fi

if [ ! -f "$2" ]
then
   echo "Error: the file does not exist" 1>&2
   exit 1
fi

if [ -f "$1" ]
then
   echo "Error: already exist Overwriting" 1>&2
   rm "$1"

fi



grep -Eo 'href="[^\"]+.c"' "$2" > "$1"

sed -i -e 's|href="..|https://courses.cs.washington.edu/courses/cse374/22au|' -e 's|.$||' "$1"

exit 0